spring:
  application:
    name: ken-reserve

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      initialization-fail-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  data-initializer:
    admin-password: ${ADMIN_INIT_PASSWORD}
